version: '3'
services:
  api:
    image: exekaliburr-api
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    security_opt:
      - no-new-privileges:true
  front:
    image: exekaliburr-front
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    security_opt:
      - no-new-privileges:true
